name: jaa
description: "FIRST Tech Challenge Judge Advisor Assistant App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-15.0.dev <4.0.0'

dependencies:
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true